# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sandbox_pb2 as sandbox__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSandbox = channel.unary_unary(
                '/sandbox.SandboxService/CreateSandbox',
                request_serializer=sandbox__pb2.CreateRequest.SerializeToString,
                response_deserializer=sandbox__pb2.CreateResponse.FromString,
                _registered_method=True)
        self.DestroySandbox = channel.unary_unary(
                '/sandbox.SandboxService/DestroySandbox',
                request_serializer=sandbox__pb2.DestroyRequest.SerializeToString,
                response_deserializer=sandbox__pb2.DestroyResponse.FromString,
                _registered_method=True)
        self.CreateFile = channel.unary_unary(
                '/sandbox.SandboxService/CreateFile',
                request_serializer=sandbox__pb2.CreateFileRequest.SerializeToString,
                response_deserializer=sandbox__pb2.CreateFileResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/sandbox.SandboxService/ReadFile',
                request_serializer=sandbox__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/sandbox.SandboxService/ListFiles',
                request_serializer=sandbox__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ListFilesResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/sandbox.SandboxService/DeleteFile',
                request_serializer=sandbox__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=sandbox__pb2.DeleteFileResponse.FromString,
                _registered_method=True)
        self.ExecCommand = channel.unary_unary(
                '/sandbox.SandboxService/ExecCommand',
                request_serializer=sandbox__pb2.ExecRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ExecResponse.FromString,
                _registered_method=True)
        self.ExecCommandStream = channel.unary_stream(
                '/sandbox.SandboxService/ExecCommandStream',
                request_serializer=sandbox__pb2.ExecRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ExecStreamResponse.FromString,
                _registered_method=True)
        self.RunApplication = channel.unary_unary(
                '/sandbox.SandboxService/RunApplication',
                request_serializer=sandbox__pb2.RunAppRequest.SerializeToString,
                response_deserializer=sandbox__pb2.RunAppResponse.FromString,
                _registered_method=True)
        self.InstallDependencies = channel.unary_unary(
                '/sandbox.SandboxService/InstallDependencies',
                request_serializer=sandbox__pb2.InstallDepsRequest.SerializeToString,
                response_deserializer=sandbox__pb2.InstallDepsResponse.FromString,
                _registered_method=True)
        self.RunServer = channel.unary_unary(
                '/sandbox.SandboxService/RunServer',
                request_serializer=sandbox__pb2.RunServerRequest.SerializeToString,
                response_deserializer=sandbox__pb2.RunServerResponse.FromString,
                _registered_method=True)
        self.RunServerStream = channel.unary_stream(
                '/sandbox.SandboxService/RunServerStream',
                request_serializer=sandbox__pb2.RunServerRequest.SerializeToString,
                response_deserializer=sandbox__pb2.RunServerStreamResponse.FromString,
                _registered_method=True)
        self.RunStaticServer = channel.unary_unary(
                '/sandbox.SandboxService/RunStaticServer',
                request_serializer=sandbox__pb2.RunStaticServerRequest.SerializeToString,
                response_deserializer=sandbox__pb2.RunStaticServerResponse.FromString,
                _registered_method=True)
        self.GetServers = channel.unary_unary(
                '/sandbox.SandboxService/GetServers',
                request_serializer=sandbox__pb2.GetServersRequest.SerializeToString,
                response_deserializer=sandbox__pb2.GetServersResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/sandbox.SandboxService/HealthCheck',
                request_serializer=sandbox__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=sandbox__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class SandboxServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroySandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecCommandStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallDependencies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunServerStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunStaticServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSandbox,
                    request_deserializer=sandbox__pb2.CreateRequest.FromString,
                    response_serializer=sandbox__pb2.CreateResponse.SerializeToString,
            ),
            'DestroySandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroySandbox,
                    request_deserializer=sandbox__pb2.DestroyRequest.FromString,
                    response_serializer=sandbox__pb2.DestroyResponse.SerializeToString,
            ),
            'CreateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFile,
                    request_deserializer=sandbox__pb2.CreateFileRequest.FromString,
                    response_serializer=sandbox__pb2.CreateFileResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=sandbox__pb2.ReadFileRequest.FromString,
                    response_serializer=sandbox__pb2.ReadFileResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=sandbox__pb2.ListFilesRequest.FromString,
                    response_serializer=sandbox__pb2.ListFilesResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=sandbox__pb2.DeleteFileRequest.FromString,
                    response_serializer=sandbox__pb2.DeleteFileResponse.SerializeToString,
            ),
            'ExecCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecCommand,
                    request_deserializer=sandbox__pb2.ExecRequest.FromString,
                    response_serializer=sandbox__pb2.ExecResponse.SerializeToString,
            ),
            'ExecCommandStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecCommandStream,
                    request_deserializer=sandbox__pb2.ExecRequest.FromString,
                    response_serializer=sandbox__pb2.ExecStreamResponse.SerializeToString,
            ),
            'RunApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.RunApplication,
                    request_deserializer=sandbox__pb2.RunAppRequest.FromString,
                    response_serializer=sandbox__pb2.RunAppResponse.SerializeToString,
            ),
            'InstallDependencies': grpc.unary_unary_rpc_method_handler(
                    servicer.InstallDependencies,
                    request_deserializer=sandbox__pb2.InstallDepsRequest.FromString,
                    response_serializer=sandbox__pb2.InstallDepsResponse.SerializeToString,
            ),
            'RunServer': grpc.unary_unary_rpc_method_handler(
                    servicer.RunServer,
                    request_deserializer=sandbox__pb2.RunServerRequest.FromString,
                    response_serializer=sandbox__pb2.RunServerResponse.SerializeToString,
            ),
            'RunServerStream': grpc.unary_stream_rpc_method_handler(
                    servicer.RunServerStream,
                    request_deserializer=sandbox__pb2.RunServerRequest.FromString,
                    response_serializer=sandbox__pb2.RunServerStreamResponse.SerializeToString,
            ),
            'RunStaticServer': grpc.unary_unary_rpc_method_handler(
                    servicer.RunStaticServer,
                    request_deserializer=sandbox__pb2.RunStaticServerRequest.FromString,
                    response_serializer=sandbox__pb2.RunStaticServerResponse.SerializeToString,
            ),
            'GetServers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServers,
                    request_deserializer=sandbox__pb2.GetServersRequest.FromString,
                    response_serializer=sandbox__pb2.GetServersResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=sandbox__pb2.HealthCheckRequest.FromString,
                    response_serializer=sandbox__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sandbox.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sandbox.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/CreateSandbox',
            sandbox__pb2.CreateRequest.SerializeToString,
            sandbox__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroySandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/DestroySandbox',
            sandbox__pb2.DestroyRequest.SerializeToString,
            sandbox__pb2.DestroyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/CreateFile',
            sandbox__pb2.CreateFileRequest.SerializeToString,
            sandbox__pb2.CreateFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/ReadFile',
            sandbox__pb2.ReadFileRequest.SerializeToString,
            sandbox__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/ListFiles',
            sandbox__pb2.ListFilesRequest.SerializeToString,
            sandbox__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/DeleteFile',
            sandbox__pb2.DeleteFileRequest.SerializeToString,
            sandbox__pb2.DeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/ExecCommand',
            sandbox__pb2.ExecRequest.SerializeToString,
            sandbox__pb2.ExecResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecCommandStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sandbox.SandboxService/ExecCommandStream',
            sandbox__pb2.ExecRequest.SerializeToString,
            sandbox__pb2.ExecStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/RunApplication',
            sandbox__pb2.RunAppRequest.SerializeToString,
            sandbox__pb2.RunAppResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstallDependencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/InstallDependencies',
            sandbox__pb2.InstallDepsRequest.SerializeToString,
            sandbox__pb2.InstallDepsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/RunServer',
            sandbox__pb2.RunServerRequest.SerializeToString,
            sandbox__pb2.RunServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunServerStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sandbox.SandboxService/RunServerStream',
            sandbox__pb2.RunServerRequest.SerializeToString,
            sandbox__pb2.RunServerStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunStaticServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/RunStaticServer',
            sandbox__pb2.RunStaticServerRequest.SerializeToString,
            sandbox__pb2.RunStaticServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/GetServers',
            sandbox__pb2.GetServersRequest.SerializeToString,
            sandbox__pb2.GetServersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/HealthCheck',
            sandbox__pb2.HealthCheckRequest.SerializeToString,
            sandbox__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
